spring:
  config:
    activate:
      on-profile: secret-dev
  datasource:
    url:
    username:
    password:
  data:
    redis:
      host:
      port: 6379
  mail:
    username: ""
    password: ""
auth:
  jwt:
    secret:
    access-expire:
    refresh-expire:
  x-api-key:
