spring:
  config:
    activate:
      on-profile: secret-local
  datasource:
    url: jdbc:h2:mem:kotlin-clean-architecture-multimodule;MODE=PostgreSQL;
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: ""
    password: ""
auth:
  jwt:
    secret: "a9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x9y8z7"
    access-expire: 7200
    refresh-expire: 604800
  x-api-key: abcd1234-ef56-7890-ghij-1234567890kl
